blog/urls.py
from django.conf.urls import url
from blog.views import current_datetime, get_post, blog

urlpatterns = [
    #url(r'^$', current_datetime),
    url(r'^$', blog, name='articles'),
    url(r'^(?P<id>[0-9]+)/$', get_post, name='post'),
    url(r'^(?P<year>[0-9]{4})/$', current_datetime, name='post_year'),
]

first/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from blog.views import current_datetime, get_index, GoogleView
from django.conf import settings
from django.conf.urls.static import static

from comment.views import CommentViews
#from page.views import get_page


urlpatterns = [
    url(r'^$', get_index, name='index_page'),
    url(r'^current_datatime/$', current_datetime),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLSmi
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^posts/', include('blog.urls', namespace="posts")),
    url(r'^post/', include('blog.urls', namespace="post")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^comments_add/(?P<id>\d+)/$', CommentViews.as_view(), name="comment_add"),
    #url(r'^page/(?P<slug>\S+)/$', get_page, name="page"),
    url(r'^i18n/', include('django.conf.urls.i18n')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

article/models.py
from django.db import models

# Create your models here.

blog/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = RichTextField()
    image = models.ImageField(upload_to="blog_image", blank=True, null=True, default=None)
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    publish = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_comment(self):
        from comment.models import Comments
        comments = Comments.objects.filter(article=self.id, publish=True)
        return comments

    def get_absolute_url(self):
        return reverse('post:post', args=[self.id])


# Create your models here.

comment/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from blog.models import Post


class Comments(models.Model):
    body = models.TextField()
    author = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Post)
    publish = models.BooleanField(default=False)

    def __str__(self):
        return self.body

comment/forms.py
from django import forms

class CommentForm(forms.Form):
    body = forms.CharField(label='Comment Body', max_length=100, widget=forms.Textarea)

article/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render, render_to_response, redirect, get_object_or_404

# Create your views here.
from django.http import HttpResponse, JsonResponse
import datetime

from django.views.decorators.cache import cache_page
from django.views.generic import RedirectView
from django.core.cache import cache

from blog.models import Post
from comment.forms import CommentForm


def current_datetime(request, year=datetime.datetime.now().year):
    cache.clear()
    now = datetime.datetime.now()
    html = "<html><body><h1>It is now %s.</h1></body></html>" % now
    if request.method == "GET":
        html = "<html><body><h1>It is now %s.</h1> %s </body></html>" % (now, year)
    return HttpResponse(html)

# @cache_page(60 * 15, key_prefix="site1", cache="filecache")
def get_index(request):
    posts = Post.objects.filter(publish=True)
    # return render(request, 'index.html', {'nowwwww': now})
    return render(request, 'index.html', locals())

def blog(request):
    posts = Post.objects.filter(publish=True)
    # return render(request, 'index.html', {'nowwwww': now})
    return render(request, 'blog/articles.html', locals())

def get_post(request, id):
    post = get_object_or_404(Post, id=id, publish=True)
    form = CommentForm()
    return render(request, 'blog/blog.html', {'post': post, 'form': form})

# def google(request):
#     return redirect('http://google.kg')


class GoogleView(RedirectView):
    url = 'http://google.kg/'
# Create your views here.

comment/views.py
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.urls import reverse
from django.views import View

from blog.models import Post
from comment.forms import CommentForm
from comment.models import Comments


class CommentViews(View):
    def get(self, request, id):
        return redirect(reverse('index_page'))

    def post(self, request, id):
        form = CommentForm(request.POST)
        if form.is_valid():
            article = get_object_or_404(Post, id=id)
            comment = Comments(
                body=request.POST['body'],
                article=article,
                author=request.user
            )
            comment.save()
        return redirect(request.META['HTTP_REFERER'])

blog/templates/blog/articles.html
{% extends 'base.html' %}

{% block title %}
Index Page
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                {% for post in posts %}
                <div class="post-preview">
                    <a href="{% url 'posts:post' post.id %}">
                        <h2 class="post-title">
                            {{ post.title }}
                        </h2>
                        <h3 class="post-subtitle">
                            <p>{{ post.text|safe|truncatewords:10 }}</p>
                        </h3>
                    </a>
                    <p class="post-meta">
                        <b>Posted by </b><a href="#">{{ post.author }}</a> on {{ post.created_date }}</p>
                        <b>Update </b>{{ post.date_update }}
                        <b>Comments </b>
                    </p>
                </div>
                <hr>
                {% empty %}
                    <div class="post-preview">
                        <h2 class="post-title">
                            Not publish article
                        </h2>
                    </div>
                <hr>
                {% endfor%}
                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="#">Older Posts &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

blog/templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ post.title }}{% endblock %}
{% block header %}
     <header style="background-image: url('{% static 'img/post.jpg' %}')">
        <div class="header-content">
            <div class="header-content-inner">
                <h1> {{ post.title|safe }}</h1>
                <hr>
                <p>
                    <b>Posted by </b><a href="#">{{ post.author }}</a> on {{ post.created_date }}</p>
                    <b>Update </b>{{ post.date_update }}
                    <b>Comments </b>
                </p>
            </div>
        </div>
    </header>

{% endblock %}
{% block content %}

    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                {{ post.text|safe }}
                </div>
            </div>
        </div>
    </article>
    <div class="col-lg-8 col-lg-offset-2 text-center"
    <h2>Comments</h2>
            {% csrf_token %}
    <form action="{% url 'comment_add' post.id %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Send">
    </form>
    {% for comment in post.get_comment %}
        <p>Author {{ comment.author }}</p>
        <p>{{ comment.body }}</p>
    {% empty %}
    <p>Not Comments</p>
    {% endfor %}
    </div>
{% endblock %}

static_files/grappelli/tinymce/examples/templates/layout1.htm
<table border="1">
	<thead>
		<tr>
			<td>Column 1</td>
			<td>Column 2</td>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td>Username: {$username}</td>
			<td>Staffid: {$staffid}</td>
		</tr>
	</tbody>
</table>

static_files/grappelli/tinymce/examples/templates/snippet1.htm
This is just some <strong>code</strong>.

templates/index.html
{% extends 'base.html' %}

{% block title %}
Index Page
{% endblock %}